---
- name: Nginx | Install and configure NGINX!
  hosts: web
  become: true
  vars: 
    nginx_listen_port: 8080

  tasks:
  - name: update
    apt: update_cache=yes
  
  - name: NGINX | Install NGINX!
    apt:
      name: nginx
      state: latest
    notify: 
      - restart nginx
    tags: 
      - nginx-package

  - name: NGINX | Create NGINX config file from template
    template:
      src: templates/nginx.conf.j2
      dest: /tmp/nginx.conf
      tags: 
        - nginx-configuration
    notify: 
      - reload nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded
